server:
  port: 8801
eureka:
  instance:
    hostname: tcs-poc-ms-eurekaserver-ca-i1
    appname: tcs-poc-ms-eurekaserver-ca-i1
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://tcs-poc-ms-eurekaserver-us-i2.us-east-1.elasticbeanstalk.com/eureka/
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
    batch-replication: true
   